Несколько изменений
htmlacademy-react/1762019-six-cities-8 pull request #14
Opened 2021-11-04 21:02 UTC by alexlyzh

1. Реализует функцию добавления в избранное
2. Карта больше не масштабируется при случайном скролле

2021-11-06 16:29 UTC, Antoshka007 requested changes
Круто 👍
Есть пару замечаний

2021-11-06 16:29 UTC, Antoshka007 commented on project/src/components/login-page/login-page.tsx
> +  const randomCityName = useMemo(() => getRandomCityName(), []);
Это зачем?)

2021-11-06 16:29 UTC, Antoshka007 commented on project/src/components/main-page/main-page.tsx
> +  const offersInCity = getCitySortedOffers(state);
Можно просто:
```suggestion
  const offersInCity = useSelector(getCitySortedOffers);
```
И `getFullState` не нужен.

2021-11-06 16:29 UTC, Antoshka007 commented on project/src/components/offer-card/offer-card.tsx
> +                isFavorite ? FavoritePathname.removeFromFavorites : FavoritePathname.addToFavorites,
Знание о `FavoritePathname` лучше перенести в `ActionsAPI.postFavorite`. Так как это больше относится к API, чем к представлению. А тут просто прокидывать `!isFavorite`.

2021-11-06 16:29 UTC, Antoshka007 commented on project/src/components/offer-page/offer-page.tsx
> +                      isFavorite ? FavoritePathname.removeFromFavorites : FavoritePathname.addToFavorites,
Плюс не придётся дублировать логику `isFavorite ? FavoritePathname.removeFromFavorites : FavoritePathname.addToFavorites` во всех кнопках, если она будет внутри `ActionsAPI.postFavorite`.

2021-11-06 16:29 UTC, Antoshka007 commented on project/src/hooks/useMap.tsx
> +      instance.addEventListener('mouseout', () => instance.scrollWheelZoom.disable());
Не забывай удалять эти обработчики. Сборщик мусора и сам это сделает после того, как instance пропадёт, но потенциально такая практика может привести к утечкам памяти. Лучше всегда следить за тем, чтобы все установленные обработчики снимались при дестрое.

2021-11-06 16:29 UTC, Antoshka007 commented on project/src/store/api-actions.ts
> +  postFavorite: (offerId: number, status: 1 | 0): ThunkActionResult =>
Согласно ТЗ, когда пользователь нажимает на кнопку "Добавить в избранное". 

> Если пользователь не авторизован, то выполняется перенаправление на страницу Sign In.

Сейчас этого не происходит.

2021-11-06 16:31 UTC, Antoshka007 commented on project/src/store/api-actions.ts
> +            dispatch(ActionCreator.setUser(response.data));
```suggestion
            dispatch(ActionCreator.setUser(Adapter.userToClient(response.data)));
```

2021-11-06 17:30 UTC, alexlyzh commented on project/src/components/login-page/login-page.tsx
> +  const randomCityName = useMemo(() => getRandomCityName(), []);
Иначе справа будет город меняться после каждого введенного символа в форму авторизации.

2021-11-07 18:13 UTC, Antoshka007 commented on project/src/components/login-page/login-page.tsx
> +  const randomCityName = useMemo(() => getRandomCityName(), []);
Не, зачем вообще там выводить рандомный город? Можно же просто статикой прописать. Амстердам, например. Картинка ведь у тебя не меняется)

2021-11-07 18:33 UTC, Antoshka007 commented on project/src/hooks/useMap.tsx
> +    // };
Обработчики снимаются из-за того, что срабатываем `setMap` и `useEffect` очищается.
Тут можно (и даже лучше) переписать с `const [map, setMap] = useState<Map | null>(null);` на `const map = useRef<Map | null>(null);`.
Тогда вместо:
1. `map=== null` => `map.current === null`
2. `setMap(instance);` => `map.current = instance;`
3. `return map;` => `return map.current;`

2021-11-07 18:34 UTC, merged